kind: ConfigMap
metadata:
  name: kube-lustre-config
  namespace: lustre
apiVersion: v1
data:
  configuration.json: |
    {
      "configuration1": {
        "lustre": {
          "install": true,
          "mgsnode": "k8s-lustre-1.novalocal:k8s-lustre-2.novalocal",
          "fsname": "lustrefs",
          "device": "/dev/drbd0",
          "debug": true,
          "force_create": false,
          "mountpoint": "/stor/lustrefs"
        },
        "drbd": {
          "install": true,
          "device": "/dev/drbd0",
          "port": "7788",
          "debug": true,
          "force_create": false,
          "disks": ["/dev/vdb", "/dev/vdb"]
        }
      }
    }
  daemons.json: |
    {
      "configuration1": {
         "mdt0-mgs": ["k8s-lustre-1.novalocal", "k8s-lustre-2.novalocal"],
         "ost0": ["k8s-lustre-3.novalocal", "k8s-lustre-4.novalocal"]
      }
    }
  clients.json: |
    {
      "configuration1": [
         "k8s-lustre-1.novalocal",
         "k8s-lustre-2.novalocal",
         "k8s-lustre-3.novalocal",
         "k8s-lustre-4.novalocal"
      ]
    }
